import { defineManifest } from '@crxjs/vite-plugin'

/**
 * MV3 manifest.
 *
 * Every permission is load-bearing:
 * - `scripting` + broad `host_permissions`: all page automation (reading,
 *   clicking, filling, scrolling, snapshotting) is on-demand injection into a
 *   real http(s) tab. No static content script is declared, so this extension
 *   stays out of every page until a test actually runs.
 * - `tabs` / `windows` (implied by `tabs`): opening the isolated run window,
 *   switching and closing tabs, and resolving the tab a step targets.
 * - `alarms`: MV3 service workers sleep, so `setInterval` is not a durable
 *   timer. Scheduled runs, the bridge reconnect, and the run watchdog all use
 *   `chrome.alarms` (1 minute minimum period).
 * - `storage`: cases, scripts, run history, settings — the worker keeps no
 *   in-memory state that matters.
 * - `unlimitedStorage`: run history references screenshots; the artifacts
 *   themselves live in IndexedDB, which is subject to the same quota.
 * - `sidePanel`: the UI lives in a side panel so it survives focus changes and
 *   navigation, unlike a popup.
 * - `notifications`: optional local notification when an unattended run fails.
 *
 * `tabCapture`/`debugger` are deliberately NOT requested: screenshots use
 * `chrome.tabs.captureVisibleTab`, which needs only host permissions.
 */
export default defineManifest({
  manifest_version: 3,
  name: 'WebTest Pilot',
  version: '0.1.0',
  description:
    'AI browser test automation: drive pages with any OpenAI-compatible model, save passing runs as replayable scripts, and start them from chat, a local API, or a timer.',
  minimum_chrome_version: '116',
  permissions: [
    'alarms',
    'storage',
    'unlimitedStorage',
    'tabs',
    'scripting',
    'sidePanel',
    'notifications',
  ],
  host_permissions: ['http://*/*', 'https://*/*'],
  // Generated by `node scripts/make-icons.mjs` rather than committed as opaque
  // binaries, so the mark can be adjusted without a design tool.
  icons: {
    16: 'icons/icon-16.png',
    32: 'icons/icon-32.png',
    48: 'icons/icon-48.png',
    128: 'icons/icon-128.png',
  },
  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },
  action: {
    default_title: 'Open WebTest Pilot',
    default_icon: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
    },
  },
  side_panel: {
    default_path: 'src/sidepanel/index.html',
  },
})
